version: '3.9'

services:
  db:
    image: postgres:16
    container_name: pyblock_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
      POSTGRES_DB: pyblock_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pyblock

  api:
    build: .
    container_name: pyblock_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - pyblock

volumes:
  db_data:

networks:
  pyblock:
